// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/compostos": {
            "post": {
                "description": "Recebe valores de entrada e retorna o montante acumulado ao longo do tempo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calculo"
                ],
                "summary": "Calcula juros compostos",
                "parameters": [
                    {
                        "description": "Valores de entrada para o cálculo",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Entrada"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de montantes calculados por mês",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Montante"
                            }
                        }
                    },
                    "400": {
                        "description": "Mensagem de erro para entrada inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Retorna uma resposta \"pong\" indicando que a API está ativa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCheck"
                ],
                "summary": "Verifica o status da API",
                "responses": {
                    "200": {
                        "description": "Resposta com mensagem 'pong'",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Entrada": {
            "type": "object",
            "properties": {
                "capital": {
                    "type": "number"
                },
                "parcelas": {
                    "type": "integer"
                },
                "taxa": {
                    "type": "number"
                }
            }
        },
        "main.Montante": {
            "type": "object",
            "properties": {
                "mes": {
                    "type": "integer"
                },
                "montante_acumulado": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Juros Compostos API",
	Description:      "Exemplo de API com Swagger no Gin",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
